### ISSUE TITLE
No downstream connection or no original_dst when using TPROXY and envoy.listener.original_dst

### ISSUE THREAD

**Issue by alishir** [glasnostic/envoy#1]
*Title*: *Configuring transparent TCP proxy*

*Description*:
> I tried to setup a transparent tcp proxy using envoy and tproxy. I checked the tproxy configuration with following snippet borrowed from this [cloudflare](https://blog.cloudflare.com/how-we-built-spectrum/) post and it works fine. But when I use envoy instead of the python snippet I got `original_dst_load_balancer: No downstream connection or no original_dst.` error.

*Envoy Config*:
```yaml
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8181
static_resources:
  clusters:
    - name: backend
      type: ORIGINAL_DST
      connect_timeout: 6s
      lb_policy: CLUSTER_PROVIDED
  listeners:
    name: listener_0
    transparent: true
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 50080
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          cluster: backend
          stat_prefix: bke
    listener_filters:
      - name: envoy.listener.original_dst
        typed_config: {}
```

*Python snippet for testing tproxy:*
```python
import socket

IP_TRANSPARENT = 19

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.setsockopt(socket.IPPROTO_IP, IP_TRANSPARENT, 1)

s.bind(('127.0.0.1', 50080))
s.listen(32)
print("[+] Bound to tcp://127.0.0.1:50080")
while True:
    c, (r_ip, r_port) = s.accept()
    l_ip, l_port = c.getsockname()
    print("[ ] Connection from tcp://%s:%d to tcp://%s:%d" % (r_ip, r_port, l_ip, l_port))
    c.send(b"hello world\n")
    c.close()
```
